{application,web_api,
             [{description,"An OTP application"},
              {vsn,"1.0"},
              {registered,[]},
              {mod,{web_api_app,[]}},
              {applications,[kernel,stdlib,cowboy,espool,jiffy]},
              {env,[]},
              {modules,[api_handler,elastic_lib,web_api_app,web_api_sup]},
              {maintainers,[]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
